name: Auto Comment

on: [pull_request]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add a comment
        run: |
          curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               -X POST \
               -d '{"body":"Hello @{{ github.event.pull_request.user.login }} 👋\n\nThank you for raising your pull request.\nPlease make sure you have followed our contributing guidelines. We will review it as soon as possible."}' \
               "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
